
return {}
-- return {
--   "nvim-neo-tree/neo-tree.nvim",
--   branch = "v3.x",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     "nvim-tree/nvim-web-devicons",
--     "MunifTanjim/nui.nvim",
--     'saifulapm/neotree-file-nesting-config', -- add plugin as dependency. no need any other config or setup call
--   },
--   opts = {
--     -- recommanded config for better UI
--     hide_root_node = true,
--     retain_hidden_root_indent = true,
--     filesystem = {
--       filtered_items = {
--         show_hidden_count = false,
--         never_show = {
--           '.DS_Store',
--         },
--       },
--     },
--     default_component_configs = {
--       indent = {
--         with_expanders = true,
--         expander_collapsed = '',
--         expander_expanded = '',
--       },
--     },
--     mappings = {
--       ["P"] = { "toggle_preview", config = { use_float = false, use_image_nvim = true } },
--       ["l"] = "focus_preview",
--       ["<C-b>"] = { "scroll_preview", config = { direction = 10 } },
--       ["<C-f>"] = { "scroll_preview", config = { direction = -10 } },
--     },
--     update_focused_file = {
--       enable = true,
--       update_cwd = true,
--     },
--     view = {
--       width = 30,
--       side = "left",
--       auto_resize = false,
--     },
--
--   },
--   config = function(_, opts)
--     opts.nesting_rules = require('neotree-file-nesting-config').nesting_rules
--
--     vim.keymap.set("n", "<tab>", ":Neotree filesystem reveal left<CR>", {})
--     vim.keymap.set("n", "<C-b>", ":Neotree focus buffers left<CR>", {})
--     vim.keymap.set("n", "<C-g>", ":Neotree focus git_status left<CR>", {})
--
--     require("neo-tree").setup(opts)
--   end
-- }
