# Base configurations
bind -n M-H previous-window
bind -n M-L next-window
unbind C-b
set -g prefix C-Space
bind C-space send-prefix
set -g mouse off
setw -g mode-keys vi
set -g allow-rename off

set-hook -g pane-focus-in 'select-pane -T "#{pane_current_command}"'

# Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.3'
# set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tpm'

# Gruvbox theme configurations
# set -g @tmux-gruvbox 'dark'
set -g @catppuccin_flavor 'mocha'
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# SPLIT
bind h split-window -v
bind v split-window -h
bind f set status

unbind '"'
unbind %

# status panes
set -g @catppuccin_status "on"
set -g @catppuccin_window_status_style "rounded"
set -g status-right ' #{cpu_icon} #{cpu_percentage} | #{ram_icon} #{ram_percentage} | #{battery_icon} #{battery_percentage} | %a %h-%d %H:%M '
set-option -g status-position top
set -g status-right-length 100
set -g status-left-length 100


run '~/.config/tmux/plugins/tpm/tpm'
